name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-verify:
    name: Build And Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devqaops-portfolio .

      - name: SonarCloud Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy To EC2
    runs-on: ubuntu-latest
    needs: build-and-verify
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo chown -R ec2-user:ec2-user /home/ec2-user/devqaops-portfolio
            git config --global --add safe.directory /home/ec2-user/devqaops-portfolio

            cd /home/ec2-user/devqaops-portfolio

            git fetch --all
            git reset --hard origin/main

            echo "Current deployed commit:"
            git log --oneline -1

            sudo docker stop devqaops-portfolio || true
            sudo docker rm devqaops-portfolio || true

            sudo docker build --no-cache -t devqaops-portfolio .
            sudo docker run -d -p 80:80 --name devqaops-portfolio devqaops-portfolio
